config/routes.rb
Rails.application.routes.draw do
  root "users#me"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  resource :session
  resources :passwords, param: :token

  get "me" => "users#me"

  resources :users, only: %i[show create edit update], param: :username do
    resources :posts
  end

  scope "/games" do
    namespace :tic_tac_toe do
      resources :lobbies, only: [:index, :show, :create] do
        member do
          post :join
          post :leave
          post :start
        end
      end

      resources :games, only: [:show], path: "" do
        post :make_move, on: :member
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gradient-to-br from-blue-500 via-indigo-500 to-violet-500 flex justify-start shadow-md shadow-neutral-400 rounded-b-md">
  <div class="isolate rounded-bl-md hover:bg-teal-400 mr-auto">
    <%= link_to root_path, class: "flex group items-center pr-3" do %>
      <%= inline_svg_tag('icon.svg', class: "group-hover:-rotate-35 transition-all duration-300 size-15 p-1") %>
      <span class="font-bold text-2xl text-white">Home</span>
    <% end %>
  </div>
  <div data-controller="dark-reader-listen"
    data-dark-reader-listen-target="darkThemeButton"
    class="hidden hover:bg-emerald-300 ml-auto">
    <div class="invert">
      <%= link_to "https://darkreader.org/" do %>
        <%= image_tag('dark-mode.png', class: "hover:invert size-15 p-3.5") %>
      <% end %>
    </div>
  </div>
  <div class="hover:bg-emerald-300">
    <%= link_to "https://github.com/bulgakke/beyonder" do %>
      <%= image_tag('github-mark-white.svg', class: "hover:invert size-15 p-3.5") %>
    <% end %>
  </div>
  <div class="text-white mx-10">
    <% if Current.user %>
        <%= button_to "logout", session_path, method: :delete,
          class: "w-full min-w-20 flex-1 sm:w-auto text-center rounded-lg mt-2 mx-auto px-3.5 py-2.5 bg-rose-600 hover:bg-rose-700 text-white block font-medium cursor-pointer"
        %>
    <% else %>
      <%= button_to "login", new_session_path,
        class: "w-full min-w-20 sm:w-auto text-center rounded-lg mt-2 mx-auto px-4.5 py-2.5 bg-teal-500 hover:bg-emerald-600 text-white block font-medium cursor-pointer"
      %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Beyonder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>